[package]
name = "duet_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
reqwest = { version = "0.11", features = ["json"] }
urlencoding = "2.1"

[features]
default = ["driver"]
driver = ["dep:tokio"]
